name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:  # Allows manual triggering of the workflow
    inputs:
      build_image:
        description: 'Check this to build and push the Docker image'
        required: true
        default: 'false'  # Default value can be set to 'false'
        type: boolean  # Use boolean for checkbox-like behavior
env:
  DOCKER_USERNAME: aashraf756
  DOCKER_REPO: service-user-passgenius
  DEPLOYMENT_FILE_PATH: overlays/dev/user
  MAVEN_SETTINGS_FILE_ID: df11f9a7-ff71-4d6b-80d7-f390bc7e79d6
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean package
    - name: Get Branch Name
      id: get_branch_name
      run: echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV
    - name: Set Image Tag
      id: set_image_tag
      run: echo "IMAGE_TAG=${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}:${{ github.sha::0:8 }}-${{ env.BRANCH_NAME }}" >> $GITHUB_ENV
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
    - name: Build Docker image
      if: github.event.inputs.build_image == 'true' || env.BRANCH_NAME == 'main'
      run: docker build . -t $IMAGE_TAG
    - name: Push Docker image
      if: github.event.inputs.build_image == 'true'
      run: docker push $IMAGE_TAG

