name: Java CI with Maven

on:
  push:
    branches: 
      - main
      - feature/* 
  workflow_dispatch:  # Allows manual triggering of the workflow
    inputs:
      build_image:
        description: 'Check this to build the Docker image and deploy the app'
        required: true
        default: 'false'
        type: boolean
env:
  DOCKER_USERNAME: aashraf756
  DOCKER_REPO: springboot-user-service
  DEPLOYMENT_FILE_PATH: overlays/dev/user
  MANIFEST_REPO_URL: https://github.com/anas-ash99/deployment-manifest-passgenius.git
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Update Kubernetes Manifest
      run: |
          echo 'Updating manifest ...'
          git clone ${{ env.MANIFEST_REPO_URL }} manifest-repo
          cd manifest-repo
          
    # - name: Set up JDK 21
    #   uses: actions/setup-java@v4
    #   with:
    #     java-version: '21'
    #     distribution: 'temurin'
    #     cache: maven
    
    # - name: Build with Maven
    #   run: mvn clean package
  
    # - name: Set Image Tag
    #   if: github.event.inputs.build_image == 'true' || github.ref_name == 'main'
    #   run: |
    #     hash_short="${GITHUB_SHA:0:8}"
    #     echo "IMAGE_TAG=${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}:$hash_short" >> "$GITHUB_ENV"
        
    # - name: Build Docker Image
    #   if: github.event.inputs.build_image == 'true' || github.ref_name == 'main'
    #   run: |
    #     # Build the Docker image
    #     docker build . -t $IMAGE_TAG
   
    # - name: Push Docker Image
    #   if: github.event.inputs.build_image == 'true' || github.ref_name == 'main'
    #   run: |
    #     # Log in to Docker Hub
    #     echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
    #     # Push the Docker image
    #     docker push $IMAGE_TAG
    
