name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:  # Allows manual triggering of the workflow
    inputs:
      build_image:
        description: 'Check this to build and push the Docker image'
        required: true
        default: 'false'  # Default value can be set to 'false'
        type: boolean  # Use boolean for checkbox-like behavior
env:
  IMAGE_TAG: aashraf756/service-user-passgenius:v1.0.4
  DEPLOYMENT_FILE_PATH: overlays/dev/user
  MAVEN_SETTINGS_FILE_ID: df11f9a7-ff71-4d6b-80d7-f390bc7e79d6
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean package

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
    - name: Build Docker image
      if: github.event.inputs.build_image == 'true'
      run: docker build . -t $IMAGE_TAG
    - name: Push Docker image
      if: github.event.inputs.build_image == 'true'
      run: docker push $IMAGE_TAG

