name: Java CI with Maven

on:
  push:
    branches: 
      - main
      - feature/* 
  workflow_dispatch:  # Allows manual triggering of the workflow
    inputs:
      build_image:
        description: 'Check this to build and push the Docker image'
        required: true
        default: 'false'  # Default value can be set to 'false'
        type: boolean  # Use boolean for checkbox-like behavior
env:
  DOCKER_USERNAME: aashraf756
  DOCKER_REPO: springboot-user-service
  DEPLOYMENT_FILE_PATH: overlays/dev/user
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn clean package
    
    - name: Get Branch Name
      id: get_branch_name
      run: echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV
  
    - name: Set Image Tag
      id: set_image_tag
      if: github.event.inputs.build_image == 'true' || github.ref_name == 'main'
      run: |
        hash_short="${GITHUB_SHA:0:8}"
        echo "IMAGE_TAG=${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}:$hash_short" >> "$GITHUB_ENV"
        
    - name: Build Docker Image
      if: github.event.inputs.build_image == 'true' || github.ref_name == 'main'
      run: |
        # Build the Docker image
        docker build . -t $IMAGE_TAG
   
    - name: Push Docker Image
      if: github.event.inputs.build_image == 'true' || github.ref_name == 'main'
      run: |
        # Log in to Docker Hub
        echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
        # Push the Docker image
        docker push $IMAGE_TAG
    
