name: Java CI with Maven

on:
  push:
    branches: 
      - main
      - feature/* 
  workflow_dispatch:  # Allows manual triggering of the workflow
    inputs:
      build_image:
        description: 'Check this to build the Docker image and deploy the app'
        required: true
        default: false
        type: boolean
env:
  DOCKER_USERNAME: aashraf756
  DOCKER_REPO: springboot-user-service
  DEPLOYMENT_FILE_PATH: overlays/dev/user/deployment.yaml
  MANIFEST_REPO_URL: https://github.com/anas-ash99/deployment-manifest-passgenius.git
  MANIFEST_BRANCH_NAME: main
  MANIFEST_REPO_NAME: deployment-manifest-passgenius
  github_token: secrets.TOKEN_GITHUB
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn clean package
  
    - name: Set Image Tag
      if: github.event.inputs.build_image == 'true' || github.ref_name == 'main'
      run: |
        hash_short="${GITHUB_SHA:0:8}"
        echo "hash_short=$hash_short" >> "$GITHUB_ENV"
        echo "IMAGE_TAG=${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}:$hash_short" >> "$GITHUB_ENV"

    - name: Use the Reusable Manifest Update Action
      uses: anas-ash99/passgenius-github-actions@v1.0.1
      with:
        manifest_repo_url: ${{ env.MANIFEST_REPO_URL }}
        manifest_repo_name: ${{ env.MANIFEST_REPO_NAME }}
        manifest_branch_name: ${{ env.MANIFEST_BRANCH_NAME }}
        image_tag: ${{ env.IMAGE_TAG }}
        deployment_file_path: ${{ env.DEPLOYMENT_FILE_PATH }}
    # - name: Update Kubernetes Manifest
    #   run: |
    #       echo 'Updating manifest ...'
    #       git clone ${{ env.MANIFEST_REPO_URL }}
    #       cd ${{ env.MANIFEST_REPO_NAME }}
    #       git checkout ${{ env.MANIFEST_BRANCH_NAME }}
    #       sed -i "s|image: .*|image: ${IMAGE_TAG}|" "${DEPLOYMENT_FILE_PATH}"
    #       git config user.name github-actions[bot]
    #       git config user.email github-actions[bot]@users.noreply.github.com
    #       git add .
    #       git commit -m "update image to version ${{ env.hash_short }}"
    #       git push https://x-access-token:${{ secrets.TOKEN_GITHUB }}@github.com/anas-ash99/${{ env.MANIFEST_REPO_NAME }}.git ${{ env.MANIFEST_BRANCH_NAME }}
